lib/wisdom_tooth_web/router.ex
defmodule WisdomToothWeb.Router do
  use WisdomToothWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug WisdomTooth.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  scope "/", WisdomToothWeb do
    pipe_through [:browser]
    
    scope "/" do
      pipe_through [:authenticate_user]
      get "/juicios/buscar", JuicioController, :buscar
      get "/juicios/detalle/:id/cuaderno", JuicioController, :cuaderno
      get "/juicios/detalle/:id", JuicioController, :detalle
      resources "/juicios", JuicioController

      resources "/litigantes", LitiganteController

      get "/empresas/buscar", EmpresaController, :buscar
      resources "/empresas", EmpresaController
    
      resources "/usuarios", UsuarioController
      
      get "/", PageController, :index
    end
    
    resources "/sesiones", SesionController, only: [:new, :create, :delete]
    
  end

  # Other scopes may use custom stacks.
  # scope "/api", WisdomToothWeb do
  #   pipe_through :api
  # end
end

lib/wisdom_tooth/gestion_juicios/empresa.ex
defmodule WisdomTooth.GestionJuicios.Empresa do
  use Ecto.Schema
  import Ecto.Changeset


  schema "empresas" do
    field :nombre, :string
    field :rut, :string
    field :numero_juicios, :integer, virtual: true
    field :numero_juicios_laborales, :integer, virtual: true
    field :numero_juicios_civiles, :integer, virtual: true
    timestamps()
  end

  @doc false
  def changeset(empresa, attrs) do
    empresa
    |> cast(attrs, [:nombre, :rut])
    |> validate_required([:nombre, :rut])
    |> unique_constraint(:rut)
  end
end

lib/wisdom_tooth_web/controllers/empresa_controller.ex
defmodule WisdomToothWeb.EmpresaController do
  use WisdomToothWeb, :controller

  alias WisdomTooth.GestionJuicios
  alias WisdomTooth.GestionJuicios.Empresa

  def index(conn, params) do
    {empresas, pagination} = GestionJuicios.list_empresas_paginated(params)
    render(conn, "index.html", empresas: empresas, pagination: pagination, busqueda: nil)
  end

  def new(conn, _params) do
    changeset = GestionJuicios.change_empresa(%Empresa{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"empresa" => empresa_params}) do
    case GestionJuicios.create_empresa(empresa_params) do
      {:ok, empresa} ->
        conn
        |> put_flash(:info, "Empresa created successfully.")
        |> redirect(to: empresa_path(conn, :show, empresa))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    empresa = GestionJuicios.get_empresa!(id)
    juicios = GestionJuicios.list_juicios_for_rut(empresa.rut)
    render(conn, "show.html", empresa: empresa, juicios: juicios)
  end

  def edit(conn, %{"id" => id}) do
    empresa = GestionJuicios.get_empresa!(id)
    changeset = GestionJuicios.change_empresa(empresa)
    render(conn, "edit.html", empresa: empresa, changeset: changeset)
  end

  def update(conn, %{"id" => id, "empresa" => empresa_params}) do
    empresa = GestionJuicios.get_empresa!(id)

    case GestionJuicios.update_empresa(empresa, empresa_params) do
      {:ok, empresa} ->
        conn
        |> put_flash(:info, "Empresa updated successfully.")
        |> redirect(to: empresa_path(conn, :show, empresa))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", empresa: empresa, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    empresa = GestionJuicios.get_empresa!(id)
    {:ok, _empresa} = GestionJuicios.delete_empresa(empresa)

    conn
    |> put_flash(:info, "Empresa deleted successfully.")
    |> redirect(to: empresa_path(conn, :index))
  end

  def buscar(conn, %{"s" => busqueda, "page" => page}) do
    {empresas, pagination} = GestionJuicios.list_empresas_paginated_by_nombre(busqueda, %{"page" => page})

    render(conn, "index.html", empresas: empresas, pagination: pagination, busqueda: busqueda)
  end
  def buscar(conn, %{"s" => busqueda}), do: buscar(conn, %{"s" => busqueda, "page" => 1})
end

lib/wisdom_tooth_web/views/empresa_view.ex
defmodule WisdomToothWeb.EmpresaView do
  use WisdomToothWeb, :view
  import Phoenix.Pagination.HTML
end

lib/wisdom_tooth_web/templates/empresa/edit.html.eex
<h2>Edit Empresa</h2>

<%= render "form.html", Map.put(assigns, :action, empresa_path(@conn, :update, @empresa)) %>

<span><%= link "Back", to: empresa_path(@conn, :index) %></span>

lib/wisdom_tooth_web/templates/empresa/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :nombre, class: "control-label" %>
    <%= text_input f, :nombre, class: "form-control" %>
    <%= error_tag f, :nombre %>
  </div>

  <div class="form-group">
    <%= label f, :rut, class: "control-label" %>
    <%= text_input f, :rut, class: "form-control" %>
    <%= error_tag f, :rut %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/wisdom_tooth_web/templates/empresa/index.html.eex
<div class="ui grid">
  <%= if assigns[:busqueda] do %>
  <div class="sixteen wide column">
    <a href="/empresas/">&laquo; Ver todas</a>
  </div>
  <% end %>
  <div class="eight wide column">
    <%= if assigns[:busqueda] do %>
      <h2>Buscando "<%= @busqueda %>"
    <% else %>
      <h2>Todas las Empresas</h2>
    <% end %>
  </div>
  <div class="eight wide column">
    <form action="/empresas/buscar" method="get">
      <div class="ui fluid action input">
        <input name="s" type="text" placeholder="Buscar por Nombre..." value="<%= @busqueda %>">
        <button class="ui icon button" type="submit">
          <i class="search icon"></i>
        </button>
      </div>
  </form>
  </div>
</div>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Juicios Civiles</th>
      <th>Juicios Laborales</th>
      <th style="min-width: 110px">Rut</th>

      <th style="min-width: 50px"></th>
    </tr>
  </thead>
  <tbody>
<%= for empresa <- @empresas do %>
    <tr>
      <td><%= empresa.nombre %></td>
      <td><%= empresa.numero_juicios_civiles %></td>
      <td><%= empresa.numero_juicios_laborales %></td>
      <td><%= empresa.rut %></td>

      <td class="text-right">
        <span><%= link "Ver", to: empresa_path(@conn, :show, empresa), class: "btn btn-primary btn-sm" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
<%= render WisdomToothWeb.PaginationView, "pagination.html", conn: @conn, pagination: @pagination, busqueda: @busqueda %>
<span><%= link "Nueva Empresa", to: empresa_path(@conn, :new) %></span>

lib/wisdom_tooth_web/templates/empresa/new.html.eex
<h2>New Empresa</h2>

<%= render "form.html", Map.put(assigns, :action, empresa_path(@conn, :create)) %>

<span><%= link "Back", to: empresa_path(@conn, :index) %></span>

lib/wisdom_tooth_web/templates/empresa/show.html.eex
<div data-controller="empresa--show">
  <a href="/empresas/">&laquo; Listado de empresas</a>

  <h2><%= @empresa.nombre %> <small>RUT: <%= @empresa.rut %></small></h2>

  <div class="ui buttons change_filtro" data-action="click->empresa--show#change_filtro">
    <button class="ui button active" data-filtro="">Todos</button>
    <button class="ui button" data-filtro="Civil">Civiles</button>
    <button class="ui button" data-filtro="Laboral">Laborales</button>
  </div>

  <div class="ui floating dropdown labeled icon button">
    <i class="list alternate icon"></i>
    <span class="text">Seleccione Procedimiento</span>
    <div class="menu" data-action="click->empresa--show#change_filtro_procedimiento">
      <div class="item" data-filtro="">Todos los Procedimientos</div>
      <div class="item" data-filtro="Accesorio">Accesorio</div>
      <div class="item" data-filtro="Administrativo">Administrativo</div>
      <div class="item" data-filtro="Civil">Civil</div>
      <div class="item" data-filtro="Ejecutivo">Ejecutivo</div>
      <div class="item" data-filtro="Laboral">Laboral</div>
      <div class="item" data-filtro="Quiebra">Quiebra</div>
    </div>
  </div>

  <table id="listado_juicios" class="ui celled table">
    <thead>
      <tr>
        <th>Tipo</th>
        <th>Tipo Procedimiento</th>
        <th>Rol</th>
        <th>Fecha</th>
        <th>Caratulado</th>
        <th>Tribunal</th>

        <th></th>
      </tr>
    </thead>
    <tbody>
    <%= for juicio <- @juicios do %>
      <tr>
        <td><%= juicio.tipo %></td>
        <td><%= juicio.tipo_procedimiento %></td>
        <td><%= juicio.rol %></td>
        <td><%= juicio.fecha %></td>
        <td><%= juicio.caratulado %></td>
        <td><%= juicio.tribunal %></td>

        <td class="text-right">
          <%= if juicio.url do %>
            <span><%= link "Ver", to: juicio_path(@conn, :detalle, juicio), class: "btn btn-default btn-xs" %></span>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
</div>