lib/wisdom_tooth_web/router.ex
defmodule WisdomToothWeb.Router do
  use WisdomToothWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug WisdomTooth.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  scope "/", WisdomToothWeb do
    pipe_through [:browser]
    
    scope "/" do
      pipe_through [:authenticate_user]
      get "/juicios/buscar", JuicioController, :buscar
      get "/juicios/detalle/:id/cuaderno", JuicioController, :cuaderno
      get "/juicios/detalle/:id", JuicioController, :detalle
      resources "/juicios", JuicioController

      resources "/litigantes", LitiganteController

      get "/empresas/buscar", EmpresaController, :buscar
      resources "/empresas", EmpresaController
    
      resources "/usuarios", UsuarioController
      
      get "/", PageController, :index
    end
    
    resources "/sesiones", SesionController, only: [:new, :create, :delete]
    
  end

  # Other scopes may use custom stacks.
  # scope "/api", WisdomToothWeb do
  #   pipe_through :api
  # end
end

lib/wisdom_tooth_web/views/layout_view.ex
defmodule WisdomToothWeb.LayoutView do
  use WisdomToothWeb, :view
end

lib/wisdom_tooth_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Monitor de Juicios</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.3.2/dist/semantic.min.css">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="ui container">
      <header class="header">
        <div class="ui right floated secondary menu">
					<%= if @usuario do %>
          	<a class="item" href="/juicios">Juicios</a>
          	<a class="item" href="/empresas">Empresas</a>
						<%= link "Cerrar Sesión", to: sesion_path(@conn, :delete, @usuario), method: "delete", class: "red item"%>
					<% end %>
        </div>
        <span class="logo"></span>
      </header>

      <%= if(get_flash(@conn, :info)) do %><p class="ui info message"><%= get_flash(@conn, :info) %></p><% end %>
      <%= if(get_flash(@conn, :error)) do %><p class="ui error message"><%= get_flash(@conn, :error) %></p><% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <!-- Bootstrap v4 -->
    <script src="//code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.3.2/dist/semantic.min.js"></script>
    <!-- DataTables -->
    <script type="text/javascript" src="//cdn.datatables.net/1.10.17/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.17/css/jquery.dataTables.min.css">

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>